GET http://localhost:3001/users HTTP/1.1

###

POST http://localhost:3001/authentication/sign-up HTTP/1.1
Content-Type: application/json

{
	"username" : "usertest23",
	"password" : "passwordpassword",
	"email" : "hat8232022@gmail.com",
    "fullname": "Hatim Rachid1"
}

### 
POST http://localhost:3001/authentication/sign-in HTTP/1.1
Content-Type: application/json

{
	"username" : "usertest23",
	"password" : "passwordpassword"
}

### 
GET http://localhost:3001/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxYjBlY2IyOC1hMGE0LTRlMzQtOWMxNS0yZDFjYjk3ODI2NjAiLCJ1c2VybmFtZSI6InVzZXJ0ZXN0MjMiLCJpYXQiOjE2OTc1NTIzNDl9.wq2z8mxhXtrJjEh2jPaHYqzH_JB97WOnOQtKfusmwxY
