GET http://localhost:3001/users HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiZGI2OTRhYi01MTc0LTRkYzgtOWZkMy1lMDBjNWVlMzMyNWIiLCJ1c2VybmFtZSI6InVzZXJ0ZXN0MjMiLCJpYXQiOjE2OTc4MDQyNjJ9.kr5s5shHVj3TaqC95lmbmoz22Ysj7EvBZkJqma07tKQ

###

POST http://localhost:3001/authentication/sign-up HTTP/1.1
Content-Type: application/json

{
	"username" : "usertest23",
	"password" : "passwordpassword",
	"email" : "hat8232022@gmail.com",
    "fullname": "Hatim Rachid1"
}

### 
POST http://localhost:3001/authentication/signIn HTTP/1.1
Content-Type: application/json

{
	"username" : "usertest23",
	"password" : "passwordpassword"
}

### 
GET http://localhost:3001/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiZGI2OTRhYi01MTc0LTRkYzgtOWZkMy1lMDBjNWVlMzMyNWIiLCJ1c2VybmFtZSI6InVzZXJ0ZXN0MjMiLCJpYXQiOjE2OTc4MDQyNjJ9.kr5s5shHVj3TaqC95lmbmoz22Ysj7EvBZkJqma07tKQ
